[package]
name = "osu-file-parser"
version = "0.1.0"
edition = "2021"
authors = [ "yuu0141 <eddio0141@gmail.com>" ]
description = "Parser for .osu files written in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.22.0"
rust_decimal_macros = "1.22.0"
thiserror = "1.0.30"
strum = "0.24.0"
strum_macros = "0.24.0"
pretty_assertions = "1.2.0"
